---
title: "CodeFromProposal1"
author: "Christina Lyu"
date: "10/29/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)

library(readr)
library(dplyr)
library(ggplot2)

# read the csv file 
billionaire <- read.csv("the-billionaire-characteristics-database.csv")

#tidy up the dataset 
tidy_billionaire <- subset(billionaire, select = -c(3, 4, 5, 10, 15, 17, 21, 23, 24, 25,26))

# change the blank cell into a NA
tidy_billionaire[tidy_billionaire == ""] <- NA

without_na <- na.omit(tidy_billionaire)

# excluded NA for gender
na_gender <- subset(tidy_billionaire, !is.na(Gender))

# excluded NA for selfmade and exclude NA for gender
gender_n_Selfmade <- subset(na_gender, !is.na(Selfmade))

# change NA in Political.Connections into 0
gender_n_Selfmade$Political.Connection[is.na(gender_n_Selfmade$Political.Connection)] <- 0

# create a age group (youth, young_adult, adult, senior)
age_billionare <- gender_n_Selfmade %>% 
  mutate(age_group = ifelse((Age >= -42 & Age <= 18 & Age == 0), 'youth', ifelse((Age > 18 & Age <= 35), 'young_adult', ifelse((Age > 35 & Age <= 55), 'adult', ifelse((Age > 55), 'senior', 'other')))))

# removing age_group NA valuables
age_group_na <- subset(age_billionare, !is.na(age_group))

#removing founding year NA variables
founding_year_na <- subset(age_group_na, !is.na(Founding.Date))

#age of company 
final_data <- founding_year_na %>%
  mutate(company_age = 2016 - Founding.Date)


# remove all the na 
na_billionare <- na.omit(tidy_billionaire)
# there are only 61 observations when removed all the na from the dataset we removed some columns => not a resonable thing to do
```

```{r}
# correlation between variables
library(mosaic)
# pairs(gender_n_Selfmade)
cor(gender_n_Selfmade[,unlist(lapply(gender_n_Selfmade, is.numeric))])
```

##### the columns that we deleted 

* name 
* citizenship
* county code
* Source.of.Wealth 
* GDP.Currentus
* Notes
* Notes.2
* Generation.of.Inheretence
* Deflator.1996
* Company


```{r,warning=FALSE, message=FALSE}
library(ggplot2)

# color code by gender and shape by Selfmade or not 
ggplot(gender_n_Selfmade, aes(x = Age, y = Net.Worth.Billion, color = Gender, shape = Selfmade)) +
  geom_point()


# model of Age, Gender and Selfmade predicting the Net.Worth.Billion
mod_age_gen_self <- lm(Net.Worth.Billion ~ Age + Gender + Selfmade, gender_n_Selfmade)

summary(mod_age_gen_self)
```

```{r,warning=FALSE, message=FALSE}
gender_n_Selfmade2 <- gender_n_Selfmade[gender_n_Selfmade$Industry!="0.0", ]

# color code by Industry
ggplot(gender_n_Selfmade2, aes(x = Founding.Date, y = Net.Worth.Billion, color = Industry)) + 
  geom_point()

ggplot(gender_n_Selfmade2, aes(x = Industry, y = Net.Worth.Billion)) + geom_point()


# model of Founding date and Industry predicting the Net.Worth.Billion
mod_date_ind <- lm(Net.Worth.Billion ~ Founding.Date + Industry, gender_n_Selfmade2)

summary(mod_date_ind)

```

```{r,warning=FALSE, message=FALSE}

# color code by region
ggplot(gender_n_Selfmade, aes(x = Founding.Date, y = Net.Worth.Billion, color = Region)) + 
  geom_point()


# model of Founding date and region predicting the Net.Worth.Billion
mod_date_reg <- lm(Net.Worth.Billion ~ Founding.Date + Region, gender_n_Selfmade)

summary(mod_date_reg)

```

```{r,warning=FALSE, message=FALSE}

#color code by political connection
ggplot(gender_n_Selfmade, aes(x = Founding.Date, y = Net.Worth.Billion, color = factor(Political.Connection))) + 
  geom_point()


# model of Founding date and Political.Connection predicting the Net.Worth.Billion



mod_date_poli <- lm(Net.Worth.Billion ~ Founding.Date + factor(Political.Connection), gender_n_Selfmade)

summary(mod_date_poli)

```

```{r,warning=FALSE, message=FALSE}

# color code by the type of company 
ggplot(gender_n_Selfmade, aes(x = Age, y = Net.Worth.Billion, color = Company.type)) +
  geom_point()


# model of Founding date and Industry predicting the Net.Worth.Billion
mod_age_comp <- lm(Net.Worth.Billion ~ Age + Company.type, gender_n_Selfmade)

summary(mod_age_comp)
```

```{r,warning=FALSE, message=FALSE}

# Separate by each company type  
ggplot(gender_n_Selfmade, aes(x = Age, y = Net.Worth.Billion, color = Gender)) +
  geom_point() + 
  facet_grid(. ~Company.type)

```


```{r}
gender_n_Selfmade[complete.cases(gender_n_Selfmade), ]
```

```{r}

a <- aov(Net.Worth.Billion ~ Type.of.Wealth, data = gender_n_Selfmade)
summary(a)
# color code by the type of company 
ggplot(gender_n_Selfmade, aes(x = Founding.Date, y = Net.Worth.Billion, color = Type.of.Wealth)) +
  geom_point()
lm <- lm(log10(Net.Worth.Billion) ~ Type.of.Wealth, data = gender_n_Selfmade)
summary(lm)
plot(lm)
```

```{r}

names(final_data) <-c("Year", "Rank", "Net_Worth_Billion", "Age", "Industry_Aggregates", "Selfmade", "Type_of_Wealth", "Industry", "Relationship_to_Company", "Gender", "Sector", "Company_type", "Founding_Date", "Political_Connection", "Region", "Characteristics", "age_group", "company_age")
```

```{r}
require(leaps)

stepwise <- regsubsets(Net_Worth_Billion ~ Year + Rank + Industry_Aggregates + Selfmade + Type_of_Wealth + Industry + Relationship_to_Company + Gender + Sector + Company_type + Founding_Date + Political_Connection + Region + Characteristics + age_group + company_age, data = final_data, nbest = 1, really.big = TRUE, method = "seqrep")

with(summary(stepwise), data.frame(rsq, adjr2, cp, rss, bic, outmat))
```

```{r}
final_data[final_data$Sector == "Communications", ]
```


```{r}
final_data <- final_data %>%
  mutate(SectorCommunications = ifelse(Sector == "Communications", 1, 0)) %>%
  mutate(SectorFashion = ifelse(Sector == "fashion", 1, 0)) %>%
  mutate(SectorTechnology = ifelse(Sector == "technology", 1, 0)) %>%
  mutate(SectorFinance = ifelse(Sector == "finance", 1, 0)) %>%
  mutate(SectorSoftware = ifelse(Sector == "software", 1, 0)) %>%
  mutate(Company_typeacquired = ifelse(Company_type == "acquired", 1, 0))
```


```{r}
m <- lm(Net_Worth_Billion ~ Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired, data = final_data)
summary(m)
```

```{r}
mod_age <- lm( Net_Worth_Billion ~ Age, final_data) 
plot(mod_age)
plot(mod_age, which = 4)
plot(m, which = 4)
```


```{r}

#billionare age dividing by region
ggplot(final_data, aes(x = Age, y = Net_Worth_Billion)) + geom_point() + facet_grid(. ~Region) + geom_smooth(method = 'lm', se = FALSE)

```

```{r}
#median age for the each region
East_Asia <- subset(final_data, Region == "East Asia")
median(East_Asia$Age)

Europe <- subset(final_data, Region == "Europe")
median(Europe$Age)

Latin_America <- subset(final_data, Region == "Latin America")
median(Latin_America$Age)

Middle_East.North_Africa <- subset(final_data, Region == "Middle East/North Africa")
median(Middle_East.North_Africa$Age)

North_America <-subset(final_data, Region == "North America")
median(North_America$Age)

South_Asia <- subset(final_data, Region == "South Asia")
median(South_Asia$Age)

Subsaharan_Africa <-subset(final_data, Region == "Sub-Saharan Africa")
median(Subsaharan_Africa$Age)

```




```{r}
#transformed Net_Worth_Billion
m2 <- lm(log(Net_Worth_Billion) ~ Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired, data = final_data)
summary(m2)
plot(m2)
```





```{r}
require(mosaic)
require(Stat2Data)
require(dplyr)
set.seed(12345)
```

```{r}
#randomization
cor(Net_Worth_Billion ~ Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired, data = final_data)

cor(Net_Worth_Billion ~ shuffle(Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired), data = final_data)

rand.test1 <- do(5000) * cor(Net_Worth_Billion ~ shuffle(Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired), data = final_data)

densityplot(~cor, data=rand.test1)
```



```{r}
#bootstrap
bootstrap <- do(5000) * coef(lm(Net_Worth_Billion ~ Year + Rank + SectorCommunications + SectorFashion + SectorFinance + SectorSoftware + SectorTechnology + Company_typeacquired, data = final_data))
densityplot(~Intercept, data = final_data)
summary(bootstrap)
bootstrap %>% summarize(ds = sd(Net_Worth_Billion))
```









